Setup Auto-Sklearn

In [ ]:
!curl https://raw.githubusercontent.com/automl/auto-sklearn/master/requirements.txt | xargs -n 1 -L 1 pip3 install

In [ ]:
!pip install --upgrade scipy

In [ ]:
!pip3 install auto-sklearn

In [ ]:
# print autosklearn version
import autosklearn
print('auto-sklearn: %s' % autosklearn.__version__)

auto-sklearn: 0.14.0

In [ ]:
from pandas import read_csv
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from autosklearn.classification import AutoSklearnClassifier

import pandas as pd

In [ ]:
# import autosklearn.classification

# import autosklearn.regression

Load Dataset

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Pitch TRAINING Data V3 - Final.csv to Pitch TRAINING Data V3 - Final.csv

In [ ]:
data = 'Pitch TRAINING Data V3 - Final.csv'

df = pd.read_csv(data)

Check Dataset

In [ ]:
df.dtypes

player_number          int64
player_name           object
pitch_type            object
release_speed        float64
release_spin_rate    float64
zone                   int64
event                 object
description           object
dtype: object

In [ ]:
# check for missing values

df.isnull().sum()

player_number         0
player_name           0
pitch_type            0
release_speed         0
release_spin_rate    49
zone                  0
event                 0
description           0
dtype: int64

In [ ]:
#assert that there are no missing values in the dataframe

# assert pd.notnull(df).all().all()

In [ ]:
categorical = [var for var in df.columns if df[var].dtype=='O']

print('There are {} categorical variables\n'.format(len(categorical)))

print('The categorical variables are :\n\n', categorical)

There are 4 categorical variables

The categorical variables are :

 ['player_name', 'pitch_type', 'event', 'description']

In [ ]:
numerical = [var for var in df.columns if df[var].dtype!='O']

print('There are {} numerical variables\n'.format(len(numerical)))

print('The numerical variables are :\n\n', numerical)

There are 4 numerical variables

The numerical variables are :

 ['player_number', 'release_speed', 'release_spin_rate', 'zone']

Data Prep

In [ ]:
# Dropping 'player_number' as we have created the dummies for it
df.drop(['player_number'], axis = 1, inplace = True)

df

            player_name pitch_type  ...      event      description
0      Wainwright, Adam         CU  ...       walk             ball
1      Wainwright, Adam         FC  ...       walk             ball
2      Wainwright, Adam         FF  ...       walk             ball
3      Wainwright, Adam         FF  ...       walk             ball
4      Wainwright, Adam         FF  ...       walk             ball
...                 ...        ...  ...        ...              ...
39966   Yamaguchi, Shun         FF  ...  strikeout  swinging_strike
39967   Yamaguchi, Shun         FF  ...  strikeout  swinging_strike
39968   Yamaguchi, Shun         FF  ...  strikeout  swinging_strike
39969   Yamaguchi, Shun         FF  ...  strikeout  swinging_strike
39970   Yamaguchi, Shun         FF  ...  strikeout  swinging_strike

[39971 rows x 7 columns]

In [ ]:
# Creating dummy variable
zones = pd.get_dummies(df['zone'])

#Display zones
zones

       1   2   3   4   5   6   7   8   9   11  12  13  14
0       0   0   0   0   0   0   0   0   0   0   1   0   0
1       0   0   0   0   0   0   0   0   0   1   0   0   0
2       0   0   0   0   0   0   0   0   0   0   1   0   0
3       0   0   0   0   0   0   0   0   0   1   0   0   0
4       0   0   0   0   0   0   0   0   0   1   0   0   0
...    ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
39966   0   1   0   0   0   0   0   0   0   0   0   0   0
39967   0   1   0   0   0   0   0   0   0   0   0   0   0
39968   0   0   1   0   0   0   0   0   0   0   0   0   0
39969   0   0   0   0   1   0   0   0   0   0   0   0   0
39970   0   0   0   0   0   0   1   0   0   0   0   0   0

[39971 rows x 13 columns]

In [ ]:
# One-hot encode the data using pandas get_dummies
df = pd.get_dummies(df)

# Adding the status to the original housing dataframe
#df = pd.concat([df, zones], axis = 1)

# Dropping 'zone' as we have created the dummies for it
df.drop(['zone'], axis = 1, inplace = True)

# Display the first 5 rows
#df.iloc[:,5:].head(5)
df

       release_speed  ...  description_swinging_strike
0               75.1  ...                            0
1               83.3  ...                            0
2               88.7  ...                            0
3               89.5  ...                            0
4               88.1  ...                            0
...              ...  ...                          ...
39966           88.8  ...                            1
39967           92.6  ...                            1
39968           93.5  ...                            1
39969           93.0  ...                            1
39970           93.8  ...                            1

[39971 rows x 788 columns]

Model Construction

In [ ]:
X = df.drop(['event_home_run'], axis=1)

y = df['event_home_run']

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [ ]:
# define search
# model = AutoSklearnClassifier(time_left_for_this_task=5*60, per_run_time_limit=30)
# model = AutoSklearnClassifier(time_left_for_this_task=12*60, per_run_time_limit=120)
model = AutoSklearnClassifier()
# perform the search
model.fit(X_train, y_train)

In [ ]:
# summarize
print(model.sprint_statistics())
# evaluate best model
y_hat = model.predict(X_test)
acc = accuracy_score(y_test, y_hat)
print("Accuracy: %.3f" % acc)

auto-sklearn results:
  Dataset name: 6541d5ee-208d-11ec-8123-0242ac1c0002
  Metric: accuracy
  Best validation score: 1.000000
  Number of target algorithm runs: 68
  Number of successful target algorithm runs: 55
  Number of crashed target algorithm runs: 0
  Number of target algorithms that exceeded the time limit: 5
  Number of target algorithms that exceeded the memory limit: 8

Accuracy: 1.000

In [ ]:
y_hat

array([0, 0, 0, ..., 0, 0, 0], dtype=uint8)

In [ ]:
y_test

13644    0
22727    0
33987    0
11232    0
4441     0
        ..
37052    0
20008    0
35615    0
12983    0
3549     0
Name: event_home_run, Length: 11992, dtype: uint8

In [ ]:
from sklearn import metrics
# y_pred = [0, 1, 0, 0]
# y_true = [0, 1, 0, 1]
metrics.precision_score(y_test, y_hat)

1.0

In [ ]:
from sklearn import metrics
# y_pred = [0, 1, 0, 0]
# y_true = [0, 1, 0, 1]
metrics.recall_score(y_test, y_hat)

1.0

In [ ]:
from sklearn import metrics
# y_pred = [0, 1, 0, 0]
# y_true = [0, 1, 0, 1]
metrics.f1_score(y_test, y_hat)

1.0

In [ ]:
from sklearn import metrics
# y_pred = [0, 1, 0, 0]
# y_true = [0, 1, 0, 1]
metrics.roc_auc_score(y_test, y_hat)

1.0

In [ ]:
from sklearn import metrics
# y_pred = [0, 1, 0, 0]
# y_true = [0, 1, 0, 1]
metrics.fbeta_score(y_test, y_hat, beta=1)

1.0